### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by nosleduc** [MarkusJx/googletest-installer#4]
Hi

I tested on windows but it fails. it seems that the location where gtest will be installed is not correct.

I put the following code in my cmakelist.txt

```
if (DEFINED ENV{GITHUB_ACTIONS})
  if (WIN32)
    link_directories("D:/gtest/lib")
    include_directories("D:/gtest/include")

    set(CMAKE_CXX_FLAGS_RELEASE "/MT")
    set(CMAKE_CXX_FLAGS_DEBUG "/MTd")
  elseif (APPLE)
    link_directories("/usr/local/lib")
    include_directories("/usr/local/include")
  endif ()
endif ()
```

**Comment by MarkusJx** [comment]
Could you please provide you `action.yml` and maybe your `CMakeLists.txt`?

**Comment by nosleduc** [comment]
action.xml
```
name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Install gtest
        uses: MarkusJx/googletest-installer@v1.1

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#      - name: Test
#        working-directory: ${{github.workspace}}/build
#        # Execute tests defined by the CMake configuration.
#        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
#        run: ctest -C ${{env.BUILD_TYPE}}


```

CMakeLists.txt in the test folder 

```
project(mt-test)

#enable_testing()


list(APPEND tests num_threads_test)
list(APPEND tests parallel_for_test)


if (DEFINED ENV{GITHUB_ACTIONS})
    if (WIN32)
        link_directories("D:/gtest/lib")
        include_directories("D:/gtest/include")

        set(CMAKE_CXX_FLAGS_RELEASE "/MT")
        set(CMAKE_CXX_FLAGS_DEBUG "/MTd")
    elseif (APPLE)
        #link_directories("/usr/local/lib")
        #include_directories("/usr/local/include")
    endif ()
endif ()


find_package(GTest REQUIRED)
if (GTEST_FOUND)
    message(STATUS "GTest found")
    message(STATUS "GTest include dir: ${GTEST_INCLUDE_DIRS}")
    message(STATUS "GTest libraries: ${GTEST_LIBRARIES}")
    link_directories(${GTEST_LIBRARIES_DIR})
else ()
    message(STATUS "GTest not found")
endif ()


foreach (test ${tests})
    add_executable(${test} ${test}.cpp)

    target_include_directories(${test} PUBLIC ${GTEST_INCLUDE_DIRS})
    target_include_directories(${test} PUBLIC ../..)
    target_link_libraries(${test} ${GTEST_LIBRARIES} ${GTEST_MAIN_LIBRARIES} mt)

    # The order matters, pthread must be added after gtest on unix
    if (UNIX)
        target_link_libraries(${test} pthread)
    endif ()


    add_test(AllTests ${test})
endforeach ()


```
