### ISSUE TITLE
CXX_Path and CC_PAH is not working.

### ISSUE THREAD

**Issue by FlorianFrank** [MarkusJx/googletest-installer#5]
Hello, 
thanks for this nice gtest installer. 
I'm using the github action to run google tests on different platforms. On windows I use MINGW instead of MSVC. 
When I set the CXX_Path and CC_Path flags It detects the right compiler and sets the right CMake flags but finally builds it again using MSVC. 
![image](https://user-images.githubusercontent.com/9607858/209924008-f4ebc736-8910-4dfd-aa36-74c1b1574055.png)

**Comment by MarkusJx** [comment]
I've added a new option in order to fix this:
```yml
- name: Install gtest
  uses: MarkusJx/googletest-installer@f6511bd6fb6ef89615f0a097458353ff8ab97823
  with:
    GENERATOR: 'MinGW Makefiles'
```
